version: "3.8"
services:
  db:
    image: mysql:8
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wild_students
      - MYSQL_USER=toto
      - MYSQL_PASSWORD=root

  app:
    depends_on:
      - db
    image: docker-build-test
    ports:
      - 8000:8000
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=toto
      - DB_PASSWORD=root
      - DB_NAME=wild_students
    volumes:
      - ./:/usr/src/app

volumes:
  db_data: