version: "3.8"
services:
  app:
    depends_on:
      - migration
    container_name: express_mysql
    build:
      context: .
    ports:
      - 8000:8000
    command: ["npm", "start"]
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  migration:
    depends_on:
        - db
    build: 
      context: .
    command:
      ["npm", "run", "migrate"]
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: on-failure

  db:
    image: mysql:8
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  db_data: